# Form implementation generated from reading ui file 'braw_to_mov.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 308)
        MainWindow.setMouseTracking(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(5, 8, 45);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 351, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.labels_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.labels_layout.setContentsMargins(0, 20, 0, 0)
        self.labels_layout.setSpacing(0)
        self.labels_layout.setObjectName("labels_layout")
        self.default_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.default_label.setMaximumSize(QtCore.QSize(16777215, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.default_label.setFont(font)
        self.default_label.setStyleSheet("color: rgb(244, 244, 244);")
        self.default_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.default_label.setScaledContents(True)
        self.default_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.default_label.setWordWrap(False)
        self.default_label.setObjectName("default_label")
        self.labels_layout.addWidget(self.default_label)
        self.files_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.files_label.setMaximumSize(QtCore.QSize(16777211, 24))
        font = QtGui.QFont()
        font.setBold(False)
        self.files_label.setFont(font)
        self.files_label.setStyleSheet("color: rgb(244, 244, 244);")
        self.files_label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.files_label.setScaledContents(True)
        self.files_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.files_label.setWordWrap(False)
        self.files_label.setObjectName("files_label")
        # self.files_label.adjustSize()
        self.labels_layout.addWidget(self.files_label)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 120, 351, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.buttons_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.buttons_layout.setContentsMargins(100, 0, 100, 0)
        self.buttons_layout.setVerticalSpacing(0)
        self.buttons_layout.setObjectName("buttons_layout")
        self.convert_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.convert_button.setEnabled(False)
        self.convert_button.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.convert_button.setFont(font)
        self.convert_button.setStyleSheet("background-color: rgb(41, 104, 199);\n"
"color: rgb(244, 244, 244);")
        self.convert_button.setObjectName("convert_button")
        self.buttons_layout.addWidget(self.convert_button, 1, 0, 1, 1)
        self.select_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.select_button.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.select_button.setFont(font)
        self.select_button.setStyleSheet("background-color: rgb(41, 104, 199);\n"
"color: rgb(244, 244, 244);")
        self.select_button.setObjectName("select_button")
        self.buttons_layout.addWidget(self.select_button, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.default_label.setText(_translate("MainWindow", "The names of selected files will appear here"))
        self.files_label.setText(_translate("MainWindow", "No files is selected yet"))
        self.convert_button.setText(_translate("MainWindow", "Convert Files"))
        self.select_button.setText(_translate("MainWindow", "Select Files"))
