# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
from pathlib import PurePath
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QDialog, QFileDialog, QMainWindow, QPushButton, QTreeView


class Ui_ImageDialog(QMainWindow):


    def clicker(self):
        # open file dialog
        # fp.openClicked()
        f_ps, _ = QFileDialog.getOpenFileNames(self, 'Navigation', '', ".braw files (*.braw);;All Files (*)")

        # output  filename to screen
        if f_ps:
            f_names = [PurePath(fp).parts[-1] for fp in f_ps]
            self.label.setText(', '.join(f_names))

    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.resize(565, 428)
        # self.buttonbox = qtwidgets.qdialogbuttonbox(imagedialog)
        # self.buttonbox.setgeometry(qtcore.qrect(30, 240, 341, 32))
        # self.buttonbox.setorientation(qtcore.qt.orientation.horizontal)
        # self.buttonbox.setstandardbuttons(qtwidgets.qdialogbuttonbox.standardbutton.cancel|qtwidgets.qdialogbuttonbox.standardbutton.ok)
        # self.buttonbox.setobjectname("buttonbox")
        self.selectFilesButton = QtWidgets.QPushButton(ImageDialog)
        self.selectFilesButton.setGeometry(QtCore.QRect(10, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectFilesButton.setFont(font)
        self.selectFilesButton.setObjectName("pushButton")
        # self.label = QtWidgets.QLabel(ImageDialog)
        # self.label.setGeometry(QtCore.QRect(30, 20, 600, 51))
        # self.label.setObjectName("label")

        self.retranslateUi(ImageDialog)
        # self.buttonBox.accepted.connect(ImageDialog.accept)
        # self.buttonBox.rejected.connect(ImageDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

    def test(self):
        self.selectFilesButton.clicked.connect(self.clicker)

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Dialog"))
        self.selectFilesButton.setText(_translate("ImageDialog", "Select Files"))
        # self.label.setText(_translate("ImageDialog", "Open File:"))
