# Form implementation generated from reading ui file 'ui_imagedialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from pathlib import PurePath, Path

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog, QMainWindow

from logic import rename_files


class Ui_ImageDialog(QMainWindow):

    def setupUi(self, ImageDialog):
        ImageDialog.setObjectName("ImageDialog")
        ImageDialog.resize(565, 428)

        self.selectFilesButton = QtWidgets.QPushButton(ImageDialog)
        self.selectFilesButton.setGeometry(QtCore.QRect(10, 70, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectFilesButton.setFont(font)
        self.selectFilesButton.setObjectName("selectFilesButton")

        self.renameFilesButton = QtWidgets.QPushButton(ImageDialog)
        self.renameFilesButton.setGeometry(QtCore.QRect(10, 140, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.renameFilesButton.setFont(font)
        self.renameFilesButton.setObjectName("renameFilesButton")

        self.label = QtWidgets.QLabel(ImageDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 600, 51))
        self.label.setObjectName("label")

        self.retranslateUi(ImageDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageDialog)

        self.selectFilesButton.clicked.connect(self.select_files)
        self.renameFilesButton.clicked.connect(self.rename_files)

    def rename_files(self):
        # TODO: сделать некликабельным, пока не появятся переменные f_names, dp
        print(self.f_names)
        print(self.dp)
        rename_files(self.f_names, self.dp)

    def select_files(self):
        # open file dialog
        # fp.openClicked()
        f_ps, _ = QFileDialog.getOpenFileNames(self, 'Navigation', '', ".braw files (*.braw);;All Files (*)")

        # output  filename to screen
        if f_ps:
            self.f_names = [PurePath(fp).parts[-1] for fp in f_ps]
            self.dp = Path(f_ps[0]).parent.absolute()
            self.label.setText(', '.join(self.f_names))

    def retranslateUi(self, ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageDialog.setWindowTitle(_translate("ImageDialog", "Dialog"))
        self.selectFilesButton.setText(_translate("ImageDialog", "Select Files"))
        self.renameFilesButton.setText(_translate("ImageDialog", "Rename Files"))
        self.label.setText(_translate("ImageDialog", "Here will appear names of selected files"))
